baseURL = "https://www.benolanlokun.com/"
relativeURLs = true
languageCode = 'en-us'
title = 'Ben Olanlokun'
theme = 'paper'
publishDir = "public"
pluralizeListTitles = false
enableGitInfo = true
enableRobotsTXT = true


[markup]
  [markup.goldmark]
	[markup.goldmark.extensions]
	  [markup.goldmark.extensions.passthrough]
		enable = true
		[markup.goldmark.extensions.passthrough.delimiters]
		  block = [['\[', '\]'], ['$$', '$$']]
		  inline = [['\(', '\)'], ['$', '$']]
	[markup.goldmark.renderer]
		unsafe= true
	[markup.goldmark.parser]
	  wrapStandAloneImageWithinParagraph = false
	  [markup.goldmark.parser.attribute]
		block = true

[params]
	math = true
	[params.meta]
		favicon = false

	

[services]
  [services.disqus]
	shortname = 'ben251'

customcss = [
	"css/settings.css",
	"css/theme.css",
	"css/styles.css"
]
